baseURL = "http://blog.xcro.top/"
logoTitle = "xcrossed's blog"
archivePaginate = 5  
showArchiveCount = true  
languageCode = "zh-cn"
title = "My New Hugo Site"
theme = "ananke"
publishDir = "docs"
[params]
    toc = true